config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations], controllers: {
  sessions: "admin/sessions"
  }

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  get '/search' => 'searches#search'
  get "customers" => redirect("/customers/sign_up")   # 新規会員登録に失敗してリロードした場合のリダイレクト処理

  namespace :admin do
    root to: 'recommendation_snacks#index'
    get 'customers/:customer_id/snacks' => 'snacks#index', as: 'customer_snacks'

    resources :customers, only: [:index, :show, :edit, :update]
    resources :sakes, only: [:index, :edit, :create, :update, :destroy]

    resources :snacks, only: [:index, :show, :destroy] do
      resources :snack_comments, only: [:destroy]
    end
    resources :recommendation_snacks
  end

  scope module: :public do
    root to: 'homes#top'

    resources :sakes, only: [:index, :show] do
      resources :snacks, only: [:index, :show]
    end

    resources :customers, only: [:show, :edit, :update] do
      collection do             # collectionはidがつかない
        get :confirm_withdraw
        patch :withdraw
      end
      member do           # memberを使うとidが付与される=>”誰が”いいねしたのかわかる必要があるため
      get :favorites
      end
    end

    resources :notifications, only: [:update]

    get "search_tag" => "snacks#search_tag"

    get "snacks" => redirect("/snacks/new")  # 投稿に失敗してリロードした場合のリダイレクト処理

    resources :snacks do
      resources :snack_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sake.rb
class Sake < ApplicationRecord

  has_many :snacks, dependent: :destroy
  has_many :recommendations, dependent: :destroy

  validates :genre, presence: true, uniqueness: true

end

app/controllers/admin/sakes_controller.rb
class Admin::SakesController < ApplicationController

  def create
    @sake = Sake.new(sake_params)
    if @sake.save
      flash[:notice] = 'お酒のジャンル登録に成功しました。'
      redirect_to request.referer
    else
      @sakes = Sake.all
      flash[:notice] = 'お酒のジャンル登録に失敗しました。'
      redirect_to request.referer
    end
  end

  def index
    @sakes = Sake.all
    @sake = Sake.new
  end

  def edit
    @sake = Sake.find(params[:id])
  end

  def update
    @sake = Sake.find(params[:id])
    if @sake.update(sake_params)
      flash[:notice] = 'お酒のジャンル編集に成功しました。'
      redirect_to admin_sakes_path
    else
      flash[:notice] = 'お酒のジャンル編集に失敗しました。'
      redirect_to request.referer
    end
  end

  def destroy
    sake = Sake.find(params[:id])
    sake.destroy
    flash[:notice] = 'お酒を削除しました。'
    redirect_to admin_sakes_path
  end

  def sake_params
    params.require(:sake).permit(:genre)
  end

end

app/helpers/admin/sakes_helper.rb
module Admin::SakesHelper
end

app/views/admin/sakes/edit.html.erb
<div class="notice ml-2 mt-2">
  <%= flash[:notice] %>
</div>

<div class="container" style="margin-top: 60px; margin-left: 120px;">
  <h4>お酒ジャンル編集</h4>
</div>

<%= form_with model: @sake, url: admin_sake_path(@sake), method: :patch do |f| %>
<div class="container mb-4" style="margin-top: 60px;">
  <div class="row justify-content-center" style="margin-left: 100px;">
    <div class="col-8">
    <table class="table table-borderless">
      <tr>
        <td class="col-2" style="font-size: 20px;">ジャンル名</td>
        <td class="col-3"><%= f.text_field :genre, placeholder: 'ジャンル名' %></td>
        <td class="col-3"><%= f.submit '変更を保存', class: 'btn text-light btn-lg', style: 'background-color: #A0522D;' %></td>
      </tr>
    </table>
    </div>
  </div>
</div>
<% end %>

app/views/admin/sakes/index.html.erb
<div class="notice ml-2 mt-2">
  <%= flash[:notice] %>
</div>

<div class="container mb-5" style="margin-top: 60px; margin-left: 120px;">
  <h4>お酒ジャンル一覧・追加</h4>
</div>

<!--ジャンル登録-->
<%= form_with model: @sake, url: admin_sakes_path, method: :post do |f| %>
<div class="container mb-4">
  <div class="row justify-content-center" style="margin-left: 100px;">
    <div class="col-8">
    <table class="table table-borderless">
      <tr>
        <td class="col-2" style="font-size: 20px;">ジャンル名</td>
        <td class="col-3"><%= f.text_field :genre, placeholder: 'ジャンル名' %></td>
        <td class="col-3"><%= f.submit '新規登録', class: 'btn text-light btn-lg', style: 'background-color: #A0522D;' %></td>
      </tr>
    </table>
    </div>
  </div>
</div>
<% end %>

<!--ジャンル一覧-->
<div class="container" style="margin-bottom: 150px;">
  <div class="row justify-content-center">
    <div class="col-5">
      <table class="table table">
        <tr bgcolor="#A0522D" class="text-light">
          <th class="col-5 pl-4">ジャンル</th>
          <th></th>
          <th></th>
        </tr>
        <% @sakes.each do |sake| %>
        <tr>
          <td>
            <div class="col ml-1" style="font-size: 20px;"><%= sake.genre %></div>
          </td>
          <td>
            <div class="col d-flex justify-content-end">
              <%= link_to '編集', edit_admin_sake_path(sake.id), class: 'btn text-light', style: 'background-color: #A0522D;' %>
            </div>
          </td>
          <td>
            <div class="col">
              <%= link_to '削除', admin_sake_path(sake.id), method: :delete, "data-confirm" => "このお酒を削除してよろしいですか?", class: 'btn btn-danger' %>
            </div>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>