config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations], controllers: {
  sessions: "admin/sessions"
  }

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  get '/search' => 'searches#search'
  get "customers" => redirect("/customers/sign_up")   # 新規会員登録に失敗してリロードした場合のリダイレクト処理

  namespace :admin do
    root to: 'recommendation_snacks#index'
    get 'customers/:customer_id/snacks' => 'snacks#index', as: 'customer_snacks'

    resources :customers, only: [:index, :show, :edit, :update]
    resources :sakes, only: [:index, :edit, :create, :update, :destroy]

    resources :snacks, only: [:index, :show, :destroy] do
      resources :snack_comments, only: [:destroy]
    end
    resources :recommendation_snacks
  end

  scope module: :public do
    root to: 'homes#top'

    resources :sakes, only: [:index, :show] do
      resources :snacks, only: [:index, :show]
    end

    resources :customers, only: [:show, :edit, :update] do
      collection do             # collectionはidがつかない
        get :confirm_withdraw
        patch :withdraw
      end
      member do           # memberを使うとidが付与される=>”誰が”いいねしたのかわかる必要があるため
      get :favorites
      end
    end

    resources :notifications, only: [:update]

    get "search_tag" => "snacks#search_tag"

    get "snacks" => redirect("/snacks/new")  # 投稿に失敗してリロードした場合のリダイレクト処理

    resources :snacks do
      resources :snack_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/snack.rb
class Snack < ApplicationRecord

  belongs_to :customer, optional: true
  belongs_to :sake

  has_many :favorites, dependent: :destroy
  has_many :favorited_customers, through: :favorites, source: :customer
  has_many :snack_tags, dependent: :destroy
  has_many :tags, through: :snack_tags
  has_many :snack_comments, dependent: :destroy
  has_many :recommendations, dependent: :destroy

  with_options presence: true do
    validates :title
    validates :ingredients
    validates :process
  end
  validates :title, length: { in: 2..40 }
  validates :introduction, presence: true, length: { maximum: 100 }
  validates :ingredients, length: { maximum: 300 }
  validates :process, length: { maximum: 600 }

  # 1つの投稿に対して1人1回までしかいいねできないようにするための確認メソッド
  def favorited_by?(customer)
    if customer.instance_of?(Customer)    # Customerクラスのインスタスであればtrueを返す
      favorites.exists?(customer_id: customer.id)
    else
      false
    end
  end

  has_one_attached :image

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end

  def self.looks(word)
    if word == "perfect_match"
      Snack.where("title LIKE?", "#{word}")
    elsif word == "forward_match"
      Snack.where("title LIKE?", "#{word}%")
    elsif word == "backward_match"
      Snack.where("title LIKE?", "%#{word}")
    else
      Snack.where("title LIKE?", "%#{word}%")
    end
  end

  def save_tags(tags)
    # 既にタグあるなら全取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?

    # 共通要素取り出し
    old_tags = current_tags - tags
    new_tags = tags - current_tags

    # 古いタグ削除
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name: old_name)
    end

    # 新しいタグ作成
    new_tags.each do |new_name|
      tag = Tag.find_or_create_by(name: new_name)   # タグがすでに存在する場合はそのタグを返し存在しない場合は新しく作る
      self.tags << tag unless self.tags.include?(tag)  # 重複したタグを追加させない
    end
  end

  scope :latest, -> { order(created_at: :desc) }    #desc = 降順 => 新着順
  scope :old, -> { order(created_at: :asc) }    #asc = 昇順 => 古い順
  scope :most_favorited, -> { left_joins(:favorites)    # favoritesテーブルとsnacksテーブルの左外部結合によるテーブルの関連付け
    .group('snacks.id')    #いいね数をカウントする際に正しい結果を得るためにグループ化（snacksテーブルのid列）
    .order('COUNT(favorites.id) DESC')    #いいねが多い順
    .includes(:favorites) }     # dbへのクエリ回数を減らすためfavoritesテーブルの関連データを予め読み込む

end

app/controllers/admin/snacks_controller.rb
class Admin::SnacksController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customer = Customer.find(params[:customer_id])
    @snacks = @customer.snacks.page(params[:page])
  end

  def show
    @snack = Snack.find(params[:id])
    @customer = @snack.customer
    @snack_tags = @snack.tags
  end

  def destroy
    snack = Snack.find(params[:id])
    customer = snack.customer.id
    snack.destroy
    flash[:notice] = '投稿を削除しました。'
    redirect_to admin_customer_snacks_path(customer)
  end

end

app/helpers/admin/snacks_helper.rb
module Admin::SnacksHelper
end

app/views/admin/snacks/_detail.html.erb
<!--おつまみ詳細画面-->

<!--おつまみ情報-->
<div class="row justify-content-center" style="width: 100%; max-width: 100%;">
  <h3 style="margin-bottom: 70px; border-bottom: 6px double #000000;"><strong><%= snack.title %></strong></h3>
</div>

<div class="row">
  <div class="col mt-2">
    <%= image_tag snack.get_image(490,470) %>
  </div>
  <table class="table table-borderless col">
    <tr>
      <th class="col-7"><h5>おつまみ紹介文</h5></th>
    </tr>
    <tr>
      <td style="border: solid 2px #000000; font-size: 18px;"><%=safe_join(snack.introduction.split("\n"),tag(:br))%></td>
    </tr>
    <tr>
      <td></td>
    </tr>
    <tr>
      <td style="font-size: 18px;">合うお酒： <strong><%= snack.sake.genre %></storong></td>
    </tr>
    <tr>
      <td></td>
    </tr>
    <tr>
      <td style="font-size: 18px;">タグ：
      <% snack_tags.each do |tag| %>
        <strong><%= link_to tag.name,search_tag_path(tag_id: tag.id) %>　</storong>
      <% end %>
      </td>
    <tr>
      <td></td>
    </tr>
    <tr>
      <td>運営者による投稿</td>
    </tr>
  </table>
</div>

<!--おつまみのレシピ情報-->
<div class="row justify-content-center mt-5">
  <h4><strong>レシピ</strong></h4>
</div>

<div class="row mt-4 mb-2">
  <div class="col mr-4">
    <h5>材料</h5>
    <p class="pt-2 pb-2 pl-2 pr-2" style="width: 100%; max-width: 527px; word-break: break-word; font-size: 18px; border: solid 2px #000000;">
      <%=safe_join(snack.ingredients.split("\n"),tag(:br))%>
    </p>
  </div>
  <div class="col">
    <h5>作り方</h5>
    <p class="pt-2 pb-2 pl-2 pr-2" style="width: 100%; max-width: 527px; word-break: break-word; font-size: 18px; border: solid 2px #000000;">
      <%=safe_join(snack.process.split("\n"),tag(:br))%>
    </p>
  </div>
</div>

<div class="row ml-1">
  投稿日：<%= snack.created_at.strftime("%Y/%m/%d") %>
</div>

<!--いいね-->
<h5>
  <div id="favorite-btn_<%= snack.id %>" class="row justify-content-end mb-3" style="margin-right: 70px; margin-bottom: 70px;">
    <%= render 'public/favorites/favorite-btn', snack: snack %>
  </div>
</h5>

<!--投稿の編集＆削除-->
<% if admin_signed_in?%>
  <div class="row mt-5 justify-content-center">
    <%= link_to '編集する', edit_admin_recommendation_snack_path(snack), class: 'col-4 btn text-light btn-lg', style: 'background-color: #A0522D;' %>
  </div>
  <div class="row mt-5 mb-5 mr-3 justify-content-end">
    <%= link_to '投稿の削除', admin_recommendation_snack_path(snack), method: :delete,
    "data-confirm" => "この投稿を削除してよろしいですか?", class: 'btn btn-danger btn-sm' %>
  </div>
<% end %>

<!--コメント-->
<div class="container-6">
  <div class="row">
    <div class="col-6 comment-index">
      <%= render 'public/snack_comments/comment-index', snack_comments: snack_comments %>
    </div>
  </div>
  <div class="col-4 mt-4 ml-5"><%= link_to_next_page snack_comments, 'コメントをもっと見る', remote: true, id: 'view_more', class: 'btn text-light rounded-pill', style: 'background-color: #A0522D;' %></div>
</div>

app/views/admin/snacks/_form.html.erb
<!--おつまみ情報フォーム-->
<%= form_with model: snack, url: admin_recommendation_snacks_path do |f| %>
  <div class="row ml-5">
    <div class="col-6 pr-5">
      <table class="table table-borderless">
        <tr>
          <th style="font-size: 23px; text-decoration: underline;">おつまみ</th>
        </tr>
        <tr>
          <td>おつまみ画像</td>
          <td><%= f.file_field :image, accept: "image/*" %></td>
        </tr>
        <tr>
          <td></td>
          <td class="text-muted">※画像の拡張子はjpg・png・jpeg形式のものをご使用ください。</td>
        </tr>
        <tr>
          <td class="col-3">タイトル</td>
          <td><%= f.text_field :title, placeholder: 'タイトル（2~40文字以内）', class: 'col' %></td>
        </tr>
        <tr>
          <td>おつまみ紹介</td>
          <td><%= f.text_area :introduction, rows:'5', placeholder: 'ここに紹介文を記述します（100文字以内）', class: 'col' %></td>
        </tr>
        <tr>
          <td>お酒</td>
          <td><%= f.collection_select(:sake_id, Sake.all, :id, :genre, include_blank: "-- このおつまみに合うお酒を選択してください --") %></td>
        </tr>
        <tr>
          <td>タグ</td>
          <td><%= f.text_area :name, value: tags, rows:'3', placeholder: '和食,こってり,15分以内', class: 'col' %></td>
        </tr>
        <tr>
        <td></td>
        <td class="text-muted">※タグが複数ある場合は半角の" , "で区切ってください。</td>
      </tr>
      </table>
    </div>

    <!--レシピの材料フォーム-->
    <div class="col">
      <table class="table table-borderless">
        <tr>
          <th style="font-size: 23px; text-decoration: underline;">レシピ</th>
        </tr>
        <tr>
          <td class="col-2">材料</td>
          <td>
            <%= f.text_area :ingredients, rows: '8', class: 'col-11',
              placeholder:         # フォームでの表示上インデントが乱れています。
'（2人前）
エリンギ（小）：8本
バター：15g
にんにくチューブ：3センチ
冷凍いんげん：7~8本
(A)しょうゆ：小さじ1
(A)化学調味料：小さじ1' %>
          </td>
        </tr>
        <tr>
          <td></td>
          <td class="text-muted">※材料は300文字以内で入力してください。<br>
            ※材料ごとに改行して入力してください。<br>
            ※適量→小さじ1のようにできるだけわかりやすい表記にしてください。
          </td>
        </tr>
      </table>

      <!--レシピの作り方フォーム-->
      <table class="table table-borderless">
        <tr>
          <td class="col-2">作り方</td>
          <td><%= f.text_area :process, rows: '15', class: 'col-11',
              placeholder:               # フォームでの表示上インデントが乱れています。
'1. エリンギといんげんを食べやすい大きさにカットします。
2. フライパンを弱火にかけバターを熱します。チューブにんにくをいれバターと炒め合わせます。
3. 中火でエリンギといんげんを炒め、しんなりしたら(A)を加えて味を整えます。' %>
          </td>
        </tr>
        <tr>
          <td></td>
          <td class="text-muted">※作り方は600文字以内で入力してさい。<br>
            ※手順ごとに改行して入力してください。
          </td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row d-flex justify-content-center">
    <%= f.submit 'おすすめを登録', class: 'col-4 btn btn-lg text-light', style: 'background-color: #A0522D;' %>
  </div>

<% end %>

app/views/admin/snacks/index.html.erb
<div class="notice mt-2 ml-2">
  <%= flash[:notice] %>
</div>

<!--特定の会員のおつまみ一覧-->
<div class="container" style="margin-bottom: 120px; margin-top: 60px; margin-left: 100px;">
  <div class="row mb-5">
    <%= form_with model: @customer do |f| %>
      <h4 style="margin-left: 50px;"><%= @customer.user_name %>さんのおつまみ一覧</h4>
    <% end %>
  </div>

  <% if @snacks.present? %>
    <div class="row" style="margin-left: 150px; margin-right: 170px;">
      <%= render 'public/customers/snacks-index', snacks: @snacks %>
    </div>
  <% else %>
    <h4 class="col text-center text-muted" style="margin-top: 80px; margin-right: 50px;">
      投稿はまだありません
    </h4>
  <% end %>

  <div class="row justify-content-center">
    <%= paginate @snacks, theme: 'twitter-bootstrap-4' %>
  </div>
</div>

app/views/admin/snacks/show.html.erb
<!--特定の会員のおつまみ詳細-->
<div class="notice">
  <%= flash[:notice] %>
</div>

<%= render 'public/snacks/detail', snack: @snack, tags: @snack_tags %>