config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations], controllers: {
  sessions: "admin/sessions"
  }

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  get '/search' => 'searches#search'
  get "customers" => redirect("/customers/sign_up")   # 新規会員登録に失敗してリロードした場合のリダイレクト処理

  namespace :admin do
    root to: 'recommendation_snacks#index'
    get 'customers/:customer_id/snacks' => 'snacks#index', as: 'customer_snacks'

    resources :customers, only: [:index, :show, :edit, :update]
    resources :sakes, only: [:index, :edit, :create, :update, :destroy]

    resources :snacks, only: [:index, :show, :destroy] do
      resources :snack_comments, only: [:destroy]
    end
    resources :recommendation_snacks
  end

  scope module: :public do
    root to: 'homes#top'

    resources :sakes, only: [:index, :show] do
      resources :snacks, only: [:index, :show]
    end

    resources :customers, only: [:show, :edit, :update] do
      collection do             # collectionはidがつかない
        get :confirm_withdraw
        patch :withdraw
      end
      member do           # memberを使うとidが付与される=>”誰が”いいねしたのかわかる必要があるため
      get :favorites
      end
    end

    resources :notifications, only: [:update]

    get "search_tag" => "snacks#search_tag"

    get "snacks" => redirect("/snacks/new")  # 投稿に失敗してリロードした場合のリダイレクト処理

    resources :snacks do
      resources :snack_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
<div class="col-4 pt-1 pb-1" style="background-color: #FFB6C1;">
<h5><%= obj.errors.count %> 件のエラーが発生しました：</h5>
<h7>
  <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</h7>
</div>
<% end %>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-expand-lg navbar-dark p-1" style="background-color: #FFCC00;">
  <div class="container">
    <a class="navbar-brand text-dark" href= "/">
      <span><%= image_tag 'logo.png', size: "130x80" %></span><br>
      <h4 style="margin-left: 12px;"><strong>WithBeer</strong></h4>
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">

      　<!--キーワード検索フォーム-->
        <%= form_with url: search_path, local: true, method: :get do |f| %>
          <li>
            <div class="col mr-3">
              <%= f.text_field :word, placeholder: 'キーワードを入力', class: 'rounded-pill' %>
              <%= f.button :submit, class: "btn-sm btn-dark" do %>
                <i class="fa-solid fa-magnifying-glass"></i>
              <% end %>
            </div>
          </li>
        <% end %>

        <% if admin_signed_in? %>
          <li>
            <%= link_to '会員一覧', admin_customers_path, class: "nav-link btn text-light rounded-pill mt-1 ml-3", style: 'background-color: #A0522D;' %>
          </li>
          <li>
            <%= link_to 'お酒一覧', admin_sakes_path, class: "nav-link btn text-light rounded-pill mt-1 ml-3", style: 'background-color: #A0522D;' %>
          </li>
          <li>
            <%= link_to '今月のおすすめ履歴一覧', admin_root_path, class: "nav-link btn text-light rounded-pill mt-1 ml-3", style: 'background-color: #A0522D;' %>
          </li>
          <li>
            <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "nav-link btn text-light rounded-pill mt-1 ml-3", style: 'background-color: #A0522D;' %>
          </li>
        <% elsif customer_signed_in? %>
          <li>
            <%= link_to customer_path(current_customer), class: "nav-link btn text-light rounded-pill mt-1 ml-3", style: 'background-color: #A0522D;' do %>
              <i class="fa-regular fa-user"></i>マイページ
            <% end %>
          </li>
          <li class="dropdown">
            <button class="nav-link btn text-light rounded-pill mt-1 ml-3 dropdown-toggle" style='background-color: #A0522D;' type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if unread_notifications.any? %>
                <span class="fa-stack pb-1" style="height: 25px; width: 25px;">     <!--要素内に二つのアイコンタグの設置-->
                  <i class="fa-regular fa-bell fa-stack-1x pb-2" style="font-size: 16px; height: 25px; width: 25px;"></i>
                  <i class="fa-solid fa-circle fa-stack-xs pt-1" style="font-size: 10px; color: red; position: absolute;"></i>
                </span>
                通知
              <% else %>
                <i class="fa-solid fa-bell" style="font-size: 17px;"></i>
                通知
              <% end %>
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <% if unread_notifications.any? %>
                <small class="dropdown-item disabled">直近5件の未読の通知を表示しています</small>
                <% unread_notifications.limit(5).order(created_at: :desc).each do |notification| %>
                  <%= link_to notification.message, notification, method: :patch, class: "dropdown-item" %>
                <% end %>
              <% else %>
                <span class="dropdown-item disabled">未読の通知はありません</span>
              <% end %>
            </div>
          </li>
          <li>
            <%= link_to favorites_customer_path(current_customer) ,class: "nav-link btn text-light rounded-pill mt-1 ml-3", style: 'background-color: #A0522D;' do %>
              <i class="fa-solid fa-heart"></i>いいね一覧
            <% end %>
          </li>
          <li>
            <%= link_to new_snack_path, class: "nav-link btn text-light rounded-pill mt-1 ml-3", style: 'background-color: #A0522D;' do %>
              <i class="fa-regular fa-pen-to-square"></i>レシピを投稿
            <% end %>
          </li>
          <li>
            <%= link_to destroy_customer_session_path, method: :delete, class: "nav-link btn text-light rounded-pill mt-1 ml-3", style: 'background-color: #A0522D;' do %>
              <i class="fa-solid fa-right-from-bracket"></i>ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to customer_session_path, class: "nav-link btn text-light rounded-pill mt-1 ml-3", style: 'background-color: #A0522D;' do %>
              <i class="fa-regular fa-pen-to-square"></i>レシピを投稿
            <% end %>
          </li>
          <li>
            <%= link_to customer_session_path, class: "nav-link btn text-light rounded-pill mt-1 ml-3", style: 'background-color: #A0522D;' do %>
              <i class="fa-solid fa-right-to-bracket"></i>ログイン
            <% end %>
          </li>
          <li>
            <%= link_to 'ゲストログイン（閲覧用）', customers_guest_sign_in_path, method: :post, class: "nav-link btn text-light rounded-pill mt-1 ml-3", style: 'background-color: #A0522D;' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Withbeer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/e3566137ff.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-image: url('<%= asset_path('body_image5.png') %>');">
    <%= render 'layouts/header' %>
    <main>
      <%= yield %>
    </main>
    <footer>
      <div class="fixed-bottom text-dark" style="background-color: #FFCC00;">
        <p class="text-center mt-3">WithBeer</p>
      </div>
    </footer>
  </body>
</html>